# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set conf.properties content
        run: |
          echo "Username=${{ secrets.USERNAME }}" > src/test/resources/conf.properties
          echo "Password=${{ secrets.PASSWORD }}" >> src/test/resources/conf.properties
      - name: Set config.properties content
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > src/test/resources/config.properties
      - name: Build with Maven
        run: mvn -B package --file pom.xml
